# Travis CI build script. This gets run by github when a push is performed.
# Note you should always push to dev and then pull from master once the tests
# pass.

sudo: required

services:
    - docker

before_install:
    - docker pull roberthiggins/tournament-organiser-db
    - docker pull roberthiggins/tournament-organiser-daoserver

install:
    # DB for all tests
    - ./scripts/install -i roberthiggins/tournament-organiser-db db

    # DAO servers for system test and unit test
    - ./scripts/install -i roberthiggins/tournament-organiser-daoserver daoserver

script:
    - docker exec daoserver python -m unittest discover -s unit_tests --pattern=*.py
