# Travis CI build script. This gets run by github when a push is performed.
# Note you should always push to dev and then pull from master once the tests
# pass.

sudo: required

services:
    - docker

before_install:
    # DB for all tests
    - docker pull roberthiggins/tournament-organiser-db
    - ./scripts/install -i roberthiggins/tournament-organiser-db db
    - docker pull roberthiggins/tournament-organiser-db

    # DAO servers for system test and unit test
    - docker pull roberthiggins/tournament-organiser-daoserver
    - ./scripts/install -i roberthiggins/tournament-organiser-daoserver daoserver

script:
    - docker exec daoserver python -m unittest discover -s unit_tests --pattern=*.py
