# Travis CI build script. This gets run by github when a push is performed.
# Note you should always push to dev and then pull from master once the tests
# pass.

sudo: required

language: python

services:
    - docker

install:
    - pip install pylint

    - cp config/dev/docker-compose.yml ./docker-compose.yml
    - cp config/dev/docker-passwords.yml ./docker-passwords.yml
    - docker-compose build unittestdb
    - docker-compose up -d unittestdb
    - docker-compose build database daoserver node
    - docker-compose up -d database daoserver node
    - docker-compose build apitestdb apitestdaoserver
    - docker-compose up -d apitestdb apitestdaoserver
    - docker-compose build systemtestdb systemtestdaoserver systemtestnode
    - docker-compose up -d systemtestdb systemtestdaoserver systemtestnode
    - docker inspect unittestdb
    - docker inspect daoserver
    - docker inspect apitestdaoserver
    - docker inspect systemtestdaoserver
script:


    - docker-compose run unittest


    - bash scripts/insert_into_db apitestdb database/data/dev/basic_functions.sql
    - bash scripts/insert_into_db apitestdb database/data/dev/api_test_data.sql
    - docker-compose run apitest


    - bash scripts/insert_into_db systemtestdb database/data/dev/basic_functions.sql
    - bash scripts/insert_into_db systemtestdb database/data/dev/behaviour_test_data.sql
    - docker-compose run systemtest_functionality

    - docker-compose up --build -d selenium
    - docker inspect selenium
    - docker-compose run systemtest_usability

    - pylint $(find . -iname "*.py")
