# Travis CI build script. This gets run by github when a push is performed.
# Note you should always push to dev and then pull from master once the tests
# pass.

sudo: required

language: python

services:
    - docker

install:
    - pip install pylint

    # DB for all tests
    - ./scripts/install database

    # DAO servers for system test, unit test, api test
    - ./scripts/install daoserver

    # Frisby for API tests
    - docker build -t frisby test/frisby/

script:
    - docker exec daoserver python -m unittest discover -s unit_tests --pattern=*.py
    - docker exec -it database bash -c 'psql --file=/docker-entrypoint-initdb.d/data/dev/behaviour_test_data.sql -d "$POSTGRES_DB" -U "$POSTGRES_USER" '
    - docker run -t --link=daoserver frisby
    - pylint $(find . -iname "*.py")
