# Travis CI build script. This gets run by github when a push is performed.
# Note you should always push to dev and then pull from master once the tests
# pass.

sudo: required

language: python

services:
    - docker

install:
    - pip install pylint

    - cp config/dev/docker-compose.dev.yml ./docker-compose.yml
    - cp config/dev/docker-passwords.dev.yml ./docker-passwords.yml
    - docker-compose build
    - docker-compose up -d database daoserver webserver
    - docker inspect daoserver
script:

    - docker-compose run unittest
    - docker cp database/data/dev/behaviour_test_data.sql database:.
    - docker exec -it database bash -c 'psql --file=behaviour_test_data.sql -d "$POSTGRES_DB" -U "$POSTGRES_USER" '
    - docker-compose run apitest
    - docker-compose run systemtest


    - pylint $(find . -iname "*.py")
