# Travis CI build script. This gets run by github when a push is performed.
# Note you should always push to dev and then pull from master once the tests
# pass.

sudo: required

language: python

services:
    - docker

before_install:
    - docker pull roberthiggins/tournament-organiser-db
    - docker pull roberthiggins/tournament-organiser-daoserver
    - docker pull roberthiggins/tournament-organiser-api-test

install:
    - pip install pylint

    # DB for all tests
    - ./scripts/install -i roberthiggins/tournament-organiser-db db

    # DAO servers for system test, unit test, api test
    - ./scripts/install -i roberthiggins/tournament-organiser-daoserver daoserver

script:
    - docker exec daoserver python -m unittest discover -s unit_tests --pattern=*.py
    - docker exec -it db bash -c 'psql --file=data/dev/behaviour_test_data.sql -d "$DB_NAME"'
    - docker run -t --link=daoserver roberthiggins/tournament-organiser-api-test
    - pylint $(find . -iname "*.py")
