database:
    volumes_from:
        - dbstore
    extends:
        file: docker-compose.base.yml
        service: database

daoserver:
    links:
        - database:database
    extends:
        file: docker-compose.base.yml
        service: daoserver

unittestdb:
    extends:
        file: docker-compose.base.yml
        service: unittestdb

unittest:
    links:
        - unittestdb:database
    extends:
        file: docker-compose.base.yml
        service: unittest

webserver:
    links:
        - daoserver:daoserver
    extends:
        file: docker-compose.base.yml
        service: webserver
