database:
    extends:
        file: docker-compose.base.yml
        service: database

daoserver:
    links:
        - database
    extends:
        file: docker-compose.base.yml
        service: daoserver

unittest:
    links:
        - database
    extends:
        file: docker-compose.base.yml
        service: unittest

apitest:
    build: test/frisby
    container_name: frisby
    links:
        - daoserver

webserver:
    links:
        - daoserver
    environment:
        DEBUG: "True"
        TEMPLATE_DEBUG: "True"
    extends:
        file: docker-compose.base.yml
        service: webserver

systemtest:
    build: test/behat
    container_name: behat
    links:
        - selenium
        - daoserver
        - webserver

selenium:
    image: selenium/standalone-firefox
    container_name: selenium
    ports:
        - "4444:4444"
