database:
    extends:
        file: docker-compose.base.yml
        service: database

daoserver:
    links:
        - database:database
    extends:
        file: docker-compose.base.yml
        service: daoserver

webserver:
    links:
        - daoserver
        - node
    environment:
        DEBUG: "True"
        TEMPLATE_DEBUG: "True"
    extends:
        file: docker-compose.base.yml
        service: webserver

node:
    links:
        - daoserver
    extends:
        file: docker-compose.base.yml
        service: node

# Unit Test Specific
unittest:
    links:
        - database:database
    extends:
        file: docker-compose.base.yml
        service: unittest

# API Test Specific
apitestdb:
    extends:
        file: docker-compose.base.yml
        service: apitestdb

apitestdaoserver:
    links:
        - apitestdb:database
    extends:
        file: docker-compose.base.yml
        service: apitestdaoserver

apitest:
    links:
        - apitestdaoserver
    extends:
        file: docker-compose.base.yml
        service: apitest

# System Test Specific
systemtestdb:
    extends:
        file: docker-compose.base.yml
        service: systemtestdb

systemtestdaoserver:
    links:
        - systemtestdb:database
    extends:
        file: docker-compose.base.yml
        service: systemtestdaoserver

systemtestwebserver:
    extends:
        file: docker-compose.base.yml
        service: systemtestwebserver
    environment:
        DEBUG: "True"
        TEMPLATE_DEBUG: "True"
    links:
        - systemtestdaoserver
        - systemtestnode

systemtestnode:
    links:
        - systemtestdaoserver
    extends:
        file: docker-compose.base.yml
        service: systemtestnode

systemtest:
    extends:
        file: docker-compose.base.yml
        service: systemtest
    links:
        - selenium
        - systemtestdaoserver
        - systemtestwebserver
        - systemtestnode

selenium:
    extends:
        file: docker-compose.base.yml
        service: selenium
    links:
        - systemtestwebserver
