database:
    extends:
        file: docker-compose.base.yml
        service: database

daoserver:
    links:
        - database
    extends:
        file: docker-compose.base.yml
        service: daoserver

webserver:
    links:
        - daoserver
    environment:
        DEBUG: "True"
        TEMPLATE_DEBUG: "True"
    extends:
        file: docker-compose.base.yml
        service: webserver

# Unit Test Specific
unittest:
    links:
        - database
    extends:
        file: docker-compose.base.yml
        service: unittest

# API Test Specific
apitestdb:
    extends:
        file: docker-compose.base.yml
        service: apitestdb

apitestdaoserver:
    links:
        - apitestdb
    extends:
        file: docker-compose.base.yml
        service: apitestdaoserver

apitest:
    links:
        - apitestdaoserver
    extends:
        file: docker-compose.base.yml
        service: apitest

# System Test Specific
systemtest:
    build: test/behat
    container_name: behat
    links:
        - selenium
        - daoserver
        - webserver

selenium:
    image: selenium/standalone-firefox
    container_name: selenium
    ports:
        - "4444:4444"
