database:
    extends:
        file: docker-compose.base.yml
        service: database

daoserver:
    links:
        - database:database
    extends:
        file: docker-compose.base.yml
        service: daoserver

webserver:
    links:
        - daoserver:daoserver
    extends:
        file: docker-compose.base.yml
        service: webserver

# Unit Test Specific
unittestdb:
    extends:
        file: docker-compose.base.yml
        service: unittestdb

unittest:
    links:
        - unittestdb:database
    extends:
        file: docker-compose.base.yml
        service: unittest

# API Test Specific
apitestdb:
    extends:
        file: docker-compose.base.yml
        service: apitestdb

apitestdaoserver:
    links:
        - apitestdb:database
    extends:
        file: docker-compose.base.yml
        service: apitestdaoserver

apitest:
    links:
        - apitestdaoserver
    extends:
        file: docker-compose.base.yml
        service: apitest

# System Test Specific
systemtestdb:
    extends:
        file: docker-compose.base.yml
        service: systemtestdb

systemtestdaoserver:
    links:
        - systemtestdb:database
    extends:
        file: docker-compose.base.yml
        service: systemtestdaoserver

systemtestwebserver:
    links:
        - systemtestdaoserver:daoserver
    extends:
        file: docker-compose.base.yml
        service: systemtestwebserver

systemtest_functionality:
    extends:
        file: docker-compose.base.yml
        service: systemtest_functionality
    links:
        - systemtestwebserver

systemtest_usability:
    extends:
        file: docker-compose.base.yml
        service: systemtest_usability
    links:
        - selenium
        - systemtestdaoserver
        - systemtestwebserver

selenium:
    extends:
        file: docker-compose.base.yml
        service: selenium
    links:
        - systemtestwebserver
