database:
    extends:
        file: docker-compose.base.yml
        service: database

daoserver:
    links:
        - database:database
    extends:
        file: docker-compose.base.yml
        service: daoserver

node:
    links:
        - daoserver:daoserver
    extends:
        file: docker-compose.base.yml
        service: node

# Unit Test Specific
unittestdb:
    extends:
        file: docker-compose.base.yml
        service: unittestdb

unittest:
    links:
        - unittestdb:database
    extends:
        file: docker-compose.base.yml
        service: unittest

# API Test Specific
apitestdb:
    extends:
        file: docker-compose.base.yml
        service: apitestdb

apitestdaoserver:
    links:
        - apitestdb:database
    extends:
        file: docker-compose.base.yml
        service: apitestdaoserver

apitest:
    links:
        - apitestdaoserver
    extends:
        file: docker-compose.base.yml
        service: apitest

# System Test Specific
systemtestdb:
    extends:
        file: docker-compose.base.yml
        service: systemtestdb

systemtestdaoserver:
    links:
        - systemtestdb:database
    extends:
        file: docker-compose.base.yml
        service: systemtestdaoserver

systemtestnode:
    links:
        - systemtestdaoserver:daoserver
    extends:
        file: docker-compose.base.yml
        service: systemtestnode

systemtest_usability:
    extends:
        file: docker-compose.base.yml
        service: systemtest_usability
    links:
        - selenium
        - systemtestdaoserver
        - systemtestnode

selenium:
    extends:
        file: docker-compose.base.yml
        service: selenium
    links:
        - systemtestnode
