database:
    extends:
        file: docker-compose.base.yml
        service: database

daoserver:
    links:
        - database
    extends:
        file: docker-compose.base.yml
        service: daoserver

webserver:
    links:
        - daoserver
    environment:
        DEBUG: "True"
        TEMPLATE_DEBUG: "True"
    extends:
        file: docker-compose.base.yml
        service: webserver

# Unit Test Specific
unittest:
    links:
        - database
    extends:
        file: docker-compose.base.yml
        service: unittest

# API Test Specific
apitestdb:
    extends:
        file: docker-compose.base.yml
        service: apitestdb

apitestdaoserver:
    links:
        - apitestdb
    extends:
        file: docker-compose.base.yml
        service: apitestdaoserver

apitest:
    links:
        - apitestdaoserver
    extends:
        file: docker-compose.base.yml
        service: apitest

# System Test Specific
systemtestdb:
    extends:
        file: docker-compose.base.yml
        service: systemtestdb

systemtestdaoserver:
    links:
        - systemtestdb
    extends:
        file: docker-compose.base.yml
        service: systemtestdaoserver

systemtestwebserver:
    extends:
        file: docker-compose.base.yml
        service: systemtestwebserver
    environment:
        DEBUG: "True"
        TEMPLATE_DEBUG: "True"
    links:
        - systemtestdaoserver

systemtest:
    extends:
        file: docker-compose.base.yml
        service: systemtest
    links:
        - selenium
        - systemtestdaoserver
        - systemtestwebserver

selenium:
    extends:
        file: docker-compose.base.yml
        service: selenium
