dbpasswords:
    environment:
        POSTGRES_USER: docker
        DATABASE_PASSWORD: FuEm7l003bfd6zM
        POSTGRES_DB: to-db

webpasswords:
    environment:
        SECRET_KEY: =a)f4_+^*7%0z#a*do-20dbg%a8=czyfqjndi65z%fqva-vqxm
        ROOT_PASSWORD: root
